[patch."https://github.com/w3f/ring-vrf"]
bandersnatch_vrfs = { git = "https://github.com/w3f//ring-vrf.git", rev = "4125212" }

[workspace]
members = ["evm-client", "relayer", "sub-client", "ton-client"]
resolver = "2"
