FROM debian:bookworm-slim AS builder

RUN apt-get update && apt-get install -y \
    ca-certificates libssl3 && \
    apt-get clean

RUN mkdir -p /libs

COPY ./target/release/bridge-relayer /usr/local/bin/relayer

RUN ldd /usr/local/bin/relayer | grep "=> /" | awk '{print $3}' | xargs -I '{}' cp -v '{}' /libs/

FROM gcr.io/distroless/base-debian12

COPY --from=builder /libs/* /usr/lib/
COPY --from=builder /usr/local/bin/relayer /usr/local/bin/relayer

USER 10000

CMD ["/usr/local/bin/relayer"]