[package]
name = "evm-client"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_json = "1.0"
serde = "1.0"
anyhow = "1.0"
alloy = { version = "0.2.1", features = ["full"] }
thiserror = "1.0.63"
